sudo: required
dist: trusty # Ubuntu 14.04
services: docker # Enables docker
script:
- exec docker run --rm -i --user="$(id -u):$(id -g)" --net=none -v "$PWD":/date blang/latex:full /bin/sh -c "lualatex --shell-escape -synctex=1 -interaction=nonstopmode -halt-on-error main.tex && makeglossaries main && lualatex --shell-escape -synctex=1 -interaction=nonstopmode -halt-on-error main.tex"

